# Copyright 2026 VKrishna04
# SPDX-License-Identifier: Apache-2.0
#
# Generated by scripts/render-packaging.sh — edit that, not this.
class DevPrune < Formula
  desc "Universal, lockfile-safe workspace pruner and background dependency cleaner"
  homepage "https://devprune.vkrishna04.me"
  version "1.16.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.16.0/dev-prune-v1.16.0-darwin-arm64.tar.gz"
      sha256 "4717153f8f095795b89c0f071a2b92e907cd28b35f39a552e994bd2eedd1ddbb"
    else
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.16.0/dev-prune-v1.16.0-darwin-x64.tar.gz"
      sha256 "7cb4d0831441daf501634fa2e21651e9e69bf5caf1adda29634fc887f97d50fe"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.16.0/dev-prune-v1.16.0-linux-arm64.tar.gz"
      sha256 "3ec076aaac5ef037e2227226c18f3869acec25715999ea69c01d3743972283f5"
    else
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.16.0/dev-prune-v1.16.0-linux-x64.tar.gz"
      sha256 "b69dff7e76621496a864fd96dc6c1475b1269d58511b4a166a465332931b0795"
    end
  end

  def install
    bin.install "dev-prune"
    # The two names are one binary, and every integration dev-prune writes down — the
    # git hooks, the scheduler — records the path it was invoked from. Installing only
    # one name would make `devp` fail for anyone who read the README.
    bin.install_symlink bin/"dev-prune" => "devp"
    generate_completions_from_executable(bin/"dev-prune", "completions")
  end

  test do
    # `DEV_PRUNE_NO_AUTO_SETUP` because nothing may install itself during a formula
    # test: Homebrew's sandbox would fail the build, and a test that registers a
    # scheduled task on someone's machine is worse than no test at all.
    ENV["DEV_PRUNE_NO_AUTO_SETUP"] = "1"
    assert_match version.to_s, shell_output("#{bin}/dev-prune --version")
    assert_match version.to_s, shell_output("#{bin}/devp --version")
  end
end
