# Copyright 2026 VKrishna04
# SPDX-License-Identifier: Apache-2.0
#
# Generated by scripts/render-packaging.sh — edit that, not this.
class DevPrune < Formula
  desc "Universal, lockfile-safe workspace pruner and background dependency cleaner"
  homepage "https://devprune.vkrishna04.me"
  version "1.18.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.18.0/dev-prune-v1.18.0-darwin-arm64.tar.gz"
      sha256 "52ef3a0e542b32c72d8b765659c4c225009eefbd10f766ce106783c59d66d124"
    else
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.18.0/dev-prune-v1.18.0-darwin-x64.tar.gz"
      sha256 "4832e96143d82cefc0112d587782c3a615d8b58980095cf85345bae93f4512b3"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.18.0/dev-prune-v1.18.0-linux-arm64.tar.gz"
      sha256 "d6459e25b6c1ad6367a11f8eeae16116e1e1dcf848d05ae652935624bc02bfb4"
    else
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.18.0/dev-prune-v1.18.0-linux-x64.tar.gz"
      sha256 "f557a35c1a2a3b8a25a58bb746e57d27def47180df4939490761029c537cbc81"
    end
  end

  def install
    bin.install "dev-prune"
    # The two names are one binary, and every integration dev-prune writes down — the
    # git hooks, the scheduler — records the path it was invoked from. Installing only
    # one name would make `devp` fail for anyone who read the README.
    bin.install_symlink bin/"dev-prune" => "devp"
    generate_completions_from_executable(bin/"dev-prune", "completions")
  end

  test do
    # `DEV_PRUNE_NO_AUTO_SETUP` because nothing may install itself during a formula
    # test: Homebrew's sandbox would fail the build, and a test that registers a
    # scheduled task on someone's machine is worse than no test at all.
    ENV["DEV_PRUNE_NO_AUTO_SETUP"] = "1"
    assert_match version.to_s, shell_output("#{bin}/dev-prune --version")
    assert_match version.to_s, shell_output("#{bin}/devp --version")
  end
end
