# Copyright 2026 VKrishna04
# SPDX-License-Identifier: Apache-2.0
#
# Generated by scripts/render-packaging.sh — edit that, not this.
class DevPrune < Formula
  desc "Universal, lockfile-safe workspace pruner and background dependency cleaner"
  homepage "https://devprune.vkrishna04.me"
  version "1.14.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.14.0/dev-prune-v1.14.0-darwin-arm64.tar.gz"
      sha256 "f2e40dee4ed23b781a9d935cdba61bec5c45b581112d5fc7f57be11f1b44b075"
    else
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.14.0/dev-prune-v1.14.0-darwin-x64.tar.gz"
      sha256 "22ffddb65ed1eb68b7d631b2685427444c7a7d11069f7144426f08a23301b17f"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.14.0/dev-prune-v1.14.0-linux-arm64.tar.gz"
      sha256 "1b002e0f989141e8b6cb2780abc7797b62049a783d94f90399865fae8ab02fbc"
    else
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.14.0/dev-prune-v1.14.0-linux-x64.tar.gz"
      sha256 "dcae458151db7669bcb012db63cd9063475c48e53ac81daf4d6d3c9ab29da532"
    end
  end

  def install
    bin.install "dev-prune"
    # The two names are one binary, and every integration dev-prune writes down — the
    # git hooks, the scheduler — records the path it was invoked from. Installing only
    # one name would make `devp` fail for anyone who read the README.
    bin.install_symlink bin/"dev-prune" => "devp"
    generate_completions_from_executable(bin/"dev-prune", "completions")
  end

  test do
    # `DEV_PRUNE_NO_AUTO_SETUP` because nothing may install itself during a formula
    # test: Homebrew's sandbox would fail the build, and a test that registers a
    # scheduled task on someone's machine is worse than no test at all.
    ENV["DEV_PRUNE_NO_AUTO_SETUP"] = "1"
    assert_match version.to_s, shell_output("#{bin}/dev-prune --version")
    assert_match version.to_s, shell_output("#{bin}/devp --version")
  end
end
